// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { getSecret } from "./src/lib/loadSecrets.js"
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --require dotenv/config prisma/seed.ts",
  },
  datasource: {
    url: await getSecret("DATABASE-URL")
  },

});
