#cloud-config

package_update: true

packages:
  - docker.io
  - curl
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

runcmd:

  # Start and enable Docker
  - systemctl start docker
  - systemctl enable docker

  # Allow azureuser to run docker
  - usermod -aG docker azureuser

  # Install Azure CLI
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash

  # Install Docker Compose
  - apt install -y docker-compose